http://localhost:3000

###
GET http://localhost:3000/api/users/

###
GET http://localhost:3000/api/users/1

###
DELETE  http://localhost:3000/api/users/2

###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "firstName": "Mike",
    "lastName": "Tyson",
    "password": "boxing",
    "email": "mtyson@gmail.com",
    "friends": ["kamila@whitehouse.org"]
}

###
PATCH  http://localhost:3000/api/users/4
Content-Type: application/json

{
    "lastName": "Jackson"
}



###
GET http://localhost:3000/api/tasks/

###
GET http://localhost:3000/api/tasks/1

###
DELETE  http://localhost:3000/api/tasks/2

###
POST http://localhost:3000/api/tasks/
Content-Type: application/json

{
    "name": "Take out the trash",
    "details": "",
    "category": "Personal Errands",
    "date": "2017-01-01",
    "time": "12:00pm",
    "important": true,
    "assignedBy": null,
    "userID": 1
}

###
PATCH http://localhost:3000/api/tasks/1
Content-Type: application/json

{
    "completed": true,
}




###
GET http://localhost:3000/api/categories/

###
GET http://localhost:3000/api/categories/1

###
DELETE  http://localhost:3000/api/categories/6

###
POST http://localhost:3000/api/categories/
Content-Type: application/json

{
    "name": "Reminders",
    "userID": null
}

###
PATCH  http://localhost:3000/api/categories/1
Content-Type: application/json

{
    "name": "Schedule Events"
}