http://localhost:3001

###
GET http://localhost:3001/api/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

###
GET http://localhost:3001/api/users/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

###
DELETE  http://localhost:3001/api/users/4
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "firstName": "Mike",
    "lastName": "Tyson",
    "password": "boxing",
    "email": "mtyson@gmail.com",
    "friends": ["kamila@whitehouse.org"]
}

###
PATCH  http://localhost:3001/api/users/4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

{
    "lastName": "Jackson",
    "password": "testing"
}

###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "email": "mtyson@gmail.com",
    "password": "boxing"
}



###
GET http://localhost:3001/api/tasks/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

###
GET http://localhost:3001/api/tasks/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

###
DELETE  http://localhost:3001/api/tasks/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

###
POST http://localhost:3001/api/tasks/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

{
    "name": "Take out the trash",
    "details": "",
    "category": "Personal Errands",
    "date": "2017-01-01",
    "time": "12:00pm",
    "important": true,
    "assignedBy": null,
    "userID": 1
}

###
PATCH http://localhost:3001/api/tasks/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

{
    "completed": true,
}




###
GET http://localhost:3001/api/categories/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

###
GET http://localhost:3001/api/categories/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

###
GET http://localhost:3001/api/categories/user/example@gmail.com
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak


###
DELETE  http://localhost:3001/api/categories/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

###
POST http://localhost:3001/api/categories/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

{
    "name": "Reminders",
    "user": "example@gmail.com"
}

###
PATCH  http://localhost:3001/api/categories/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNaWtlIiwibGFzdE5hbWUiOiJUeXNvbiIsImVtYWlsIjoibXR5c29uQGdtYWlsLmNvbSIsImZyaWVuZHMiOlsia2FtaWxhQHdoaXRlaG91c2Uub3JnIl0sImlkIjo0LCJpYXQiOjE2NDkxMTQ1NDV9.BJSY5ZPN1agJg-E35mfpLyR6uRh6YX8ITCTn6FEwEak

{
    "name": "Schedule Events"
}